spring:
  config:
    activate:
      on-profile: qa

build:
  version:
    java-version: "2.5"

accounts:
  message: "welcome to the king sector here only one lion is there that is integrationtesting qa department"

  contact-details:
    name: "buddha the unknown developer"
    developer: "luddha the self thinking developer"

  on-call-support:
    - "989898989797"
    - "919919191919"
